import React from "react";
import Head from "next/head";

function MainHeading() {
  return (
    <>
      <Head>
        <title>Gamr Empire - Players with extreme gamer tags</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
    </>
  );
}

export default MainHeading;
